version: '3.7'

services:
  unboundidLdap:
    image: unboundid-ldap:latest
    hostname: unboundid-ldap
    restart: always
    ports:
      - "389:389"
    environment:
      - baseDN=dc=netplus,dc=local
      - port=389
      - additionalBindDN=cn=Manager,dc=netplus,dc=local
      - additionalBindPassword=plus321
      - LDAP_PROPS_FILE=./conf/ldap.properties
      - LDAP_LDIF_FILE=./conf/ldap.ldif